version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: mongodb
    versions:
    - 3.6.3
    - 3.6.4
    - 3.6.5
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
