FORMAT: X-1A

# Machines API 

The Example API for Dredd API Blueprint testing tool

[![Build Status](https://travis-ci.org/apiaryio/dredd-example.png?branch=master)](https://travis-ci.org/apiaryio/dredd-example)
# Group Machines

# Machines collection [/machines]

## Create a Machine [POST]
+ Request (application/json)

        {
          "type": "bulldozer",
          "name": "willy"
        }

+ Response 201 (application/json)
        
        {
          "_id": "5435542b1de4b12f6ab66b41",
          "type": "bulldozer",
          "name": "willy"
        }

## Retreive all Machines [GET]

+ Response 200 (application/json)

        [{
            "_id": "52341870ed55224b15ff07ef",
            "type": "bulldozer",
            "name": "willy"
        }]

# Machine [/machines/{id}]
+ Parameters
  + id (required,`52341870ed55224b15ff07ef`)


## Retrieve a Machine [GET]
+ Response 200 (application/json)

        {
          "type": "bulldozer",
          "name": "willy",
          "_id": "52341870ed55224b15ff07ef"
        }

## Delete a Machine [DELETE]

+ Response 204