FORMAT: X-1A

# Machines API 

# Machine [/machines/{name}]
+ Parameters
  + id (required) ... Example: `1`

## Create a Machine [POST]
+ Response 201 (application/json)

        {
          "type": "bulldozer",
          "name": "willy",
          "id": "1"
        }

## Retrieve a Machine [PUT]
+ Response 200 (text/plain)

        {
          "type": "bulldozer",
          "name": "waldo",
          "id": "1"
        }

## Update a Machine [GET]
+ Response 200 (text/plain)

        {
          "type": "bulldozer",
          "name": "waldo",
          "id": "1"
        }

## Delete Message [DELETE]
+ Response 204

# Machine Types [/machine_types/{name}]
+ Parameters
  + id (required) ... Example: `1`

## Retreive Machine type [GET]
+ Response 200 (application/json)

        {
          "name": "bulldozer"
        }

