#!/bin/sh
if [ "$CI" = "true" ]
  then
    npm install -g dredd@0.3.8
fi
./node_modules/coffee-script/bin/coffee scripts/reset_db.coffee
./node_modules/coffee-script/bin/coffee app.coffee &
sleep 3
PID=$!
dredd apiary.apib http://localhost:3000/ --hookfiles=hooks/*
RESULT=$?
kill -9 $PID
exit $RESULT