#!/bin/sh
npm install -g dredd@0.3.2
npm install -g git://github.com/apiaryio/dredd.git#netmilk/new-rest-reporter

export DREDD_REST_URL=http://api.apiary.io
export DREDD_REST_TOKEN=add0b5027298ac11e76d09ccb2032d49
export DREDD_REST_SUITE=reportingmock
export DREDD_REST_DEBUG=true

./node_modules/coffee-script/bin/coffee scripts/reset_db.coffee
./node_modules/coffee-script/bin/coffee app.coffee &
sleep 3
PID=$!
#../dredd/bin/dredd apiary.apib http://localhost:3000/ --reporter apiary
dredd apiary.apib http://localhost:3000/ --reporter apiary
RESULT=$?
kill -9 $PID
exit $RESULT
