#!/bin/sh
if [ "$CI" = "true" ]
  then
    npm update -g npm
    npm install -g dredd@0.3.14
fi
node app.js &
sleep 3
PID=$!
dredd apiary.apib http://localhost:3000/
RESULT=$?
kill -9 $PID
exit $RESULT